version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - apt update
      - apt install ffmpeg
      - cd /tmp/
      - curl -OJL https://github.com/git-lfs/git-lfs/releases/download/v2.13.3/git-lfs-linux-amd64-v2.13.3.tar.gz
      - tar xzf git-lfs-linux-amd64-v2.13.3.tar.gz
      - ./install.sh
      - cd $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - git lfs pull
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - aws s3 sync --delete ./dist s3://reclaimers-wiki-files
