version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - git submodule update --init
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://reclaimers-wiki-files/
